### ISSUE TITLE
Adding it to minecraft

### ISSUE THREAD

**Issue by KillaIbiHeem** [arrayofc/Keystrokes#1]
How do i add this to minecraft?

**Comment by leolifbom** [comment]
Hi,

Thanks for your interest in using the mod. I have went ahead and uploaded a jar for download [here](https://drive.google.com/file/d/1yMeOfn13EkINc2ZnTwh1ThpZ6Rt_uZMl/view). You can use this mod by placing it in your `.minecraft/mods` folder and running Forge 1.16.4/1.16.5.

**Comment by KillaIbiHeem** [comment]
Thankyou very much for this. I greatly appreciate it.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
