### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by Shreyas-warrior** [arrayofc/Keystrokes#2]

**Comment by Shreyas-warrior** [comment]
pls tell how to use it

**Comment by leolifbom** [comment]
Hi,

Thanks for your interest in using the mod. I have went ahead and uploaded a jar for download [here](https://drive.google.com/file/d/1yMeOfn13EkINc2ZnTwh1ThpZ6Rt_uZMl/view). You can use this mod by placing it in your `.minecraft/mods` folder and running Forge 1.16.4/1.16.5.
